# Generated by Django 4.2.1 on 2023-05-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0003_rename_expirition_date_thing_expiration_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thing',
            options={'ordering': ['expiration_date']},
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='thing',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
