# Generated by Django 4.2.1 on 2023-05-30 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0004_alter_thing_options_product_size_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thing',
            options={'ordering': ['-expiration_date']},
        ),
    ]
